name: zidf
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - pytorch>=2.0
  - torchvision
  - torchaudio
  - cudatoolkit
  - numpy>=1.24
  - scipy>=1.10
  - pandas>=2.0
  - xarray>=2023.1.0
  - netcdf4>=1.6.0
  - matplotlib>=3.7
  - seaborn>=0.12
  - scikit-learn>=1.3
  - pip
  - pip:
      - tqdm>=4.65
      - tensorboard>=2.13
      - wandb>=0.15
      - pyyaml>=6.0
