data:
  use_synthetic: true
  n_samples: 10000
  n_features: 5
  zero_ratio: 0.7
  input_len: 48
  output_len: 24

model:
  d_model: 512
  n_heads: 8
  e_layers: 2
  d_layers: 1
  dropout: 0.05
  alpha_noise: 0.1

diffusion:
  diffusion_hidden_dim: 128
  diffusion_steps: 1000
  beta_schedule: cosine

train:
  batch_size: 64
  pred_epochs: 50
  diff_epochs: 30
  pred_lr: 1e-4
  diff_lr: 1e-4
  num_workers: 4
  seed: 42

output:
  save_dir: ./checkpoints
